CREATE UNIQUE INDEX ITEM_PK ON ITEM(ITEM_ID);

SELECT * FROM USER_INDEXES WHERE TABLE_NAME = 'ITEM';   -- 인덱스 조회
DROP INDEX ITEM_PK;

-- INDEX UNIQUE SCAN
SET AUTOTRACE ON 
SELECT *
  FROM ITEM
 WHERE ITEM_ID = 11;
 
 
 
create UNIQUE INDEX UITEM_PK ON UITEM(ITEM_ID, UITEM_ID); 

--  INDEX RANGE SCAN  
SET AUTOTRACE ON 
SELECT *
  FROM UITEM
 WHERE ITEM_ID = 89;
  



CREATE INDEX ITEM_X01 ON ITEM(ITEM_NM);

-- INDEX RANGE SCAN
SET AUTOTRACE ON
SELECT *
  FROM ITEM
 WHERE ITEM_NM LIKE '밀크셰이크%';
 
 