SELECT *
  FROM ITEM
 WHERE ITEM_NM LIKE '%버거%'
 ORDER BY ITEM_NM;
 
 
ALTER SESSION SET STATISTICS_LEVEL = ALL;
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY_CURSOR(NULL, NULL, 'ALLSTATS LAST -ROWS')); 
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY_CURSOR(NULL, NULL, 'ALLSTATS LAST')); 
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY_CURSOR(NULL, NULL, 'ALLSTATS LAST +OUTLINE +ALIAS')); 

SET AUTOTRACE ON
SELECT *
  FROM ITEM
 WHERE ITEM_NM LIKE '%버거%'
 ORDER BY ITEM_NM;
 

-- TABLE ACCESS FUL 
SET AUTOTRACE ON
SELECT *
  FROM ITEM
 WHERE ITEM_NM IS NOT NULL
 ORDER BY ITEM_NM;
 
 
 
-- TABLE ACCESS BY USER ROWID
SET AUTOTRACE ON 
SELECT * 
  FROM ITEM 
WHERE ROWID = 'AAAFDLAAEAAAAFtAAA'



 