CREATE UNIQUE INDEX ITEM_PK ON ITEM(ITEM_ID);

SELECT * FROM USER_INDEXES WHERE TABLE_NAME = 'ITEM';   -- 인덱스 조회
DROP INDEX ITEM_PK;

-- INDEX UNIQUE SCAN
SET AUTOTRACE ON 
SELECT *
  FROM ITEM
 WHERE ITEM_ID = 11;
 
 
 
create UNIQUE INDEX UITEM_PK ON UITEM(ITEM_ID, UITEM_ID); 

--  INDEX RANGE SCAN  
SET AUTOTRACE ON 
SELECT *
  FROM UITEM
 WHERE ITEM_ID = 89;
  



CREATE INDEX ITEM_X01 ON ITEM(ITEM_NM);

-- INDEX RANGE SCAN
SET AUTOTRACE ON
SELECT *
  FROM ITEM
 WHERE ITEM_NM LIKE '밀크셰이크%';
 
 
-- INDEX RANGE SCAN          | ITEM_PK
SET AUTOTRACE ON 
SELECT * 
  FROM ITEM 
WHERE ITEM_ID BETWEEN 1 AND 10; 




-- INDEX FULL SCAN

SET AUTOTRACE ON 
SELECT * 
  FROM ITEM 
 WHERE ITEM_NM IS NOT NULL;
 

 
 
-- INDEX SKIP SCAN
drop index item_x01;
create index item_x01 on item( item_type_cd, item_nm);

SET AUTOTRACE ON 
SELECT * FROM ITEM WHERE ITEM_NM LIKE '한우%';


-- 선두 커럶이 조건절에 없기 때문에 index Skip Scan 이 동작합니다.
-- 생략된 컬럼 값의 종류가 적을 때는 유용하지만, 값의 종류가 많을 떄 Index Skip Scan으로 탐색하려 한다면 느린 성능으로 바뀔 수 있다.








 
